engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: true
  eslint:
    enabled: true
    channel: "eslint-3"
    config: .eslintrc.js
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.js"
  - "**.hbs"
